version: '3'
services:
  solr-artresearch:
    image: solr:8
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ./data:/var/solr
      # - ./myConfigs:/opt/solr-8.11.1/server/solr/configsets
    command:
      - solr-precreate
      - artworks
volumes:
  data:
  
