version: '3'
services:
  solr-artresearch:
    image: solr:8
    environment:
      - SOLR_HOST=${VIRTUAL_HOST}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    network_mode: nginx-docker-gen
    volumes:
      - ./data:/var/solr
      - ./server/web.xml:/opt/solr-8.11.1/server/solr-webapp/webapp/WEB-INF/web.xml
      # - ./myConfigs:/opt/solr-8.11.1/server/solr/configsets
    command:
      - solr-precreate
      - artworks
volumes:
  data:
  
