version: '3'
services:
  solr-artresearch:
    image: solr:8
    ports:
     - "8983:8983"
    volumes:
      - ./data:/var/solr
      - ./myConfigs:/opt/solr-8.11.1/server/solr/configsets
    command:
      - solr-precreate
      - artworks
volumes:
  data:
  